//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBPUpdateTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CBP_Name_Range")]
        public string CPB_Name_Range {
            get {
                return ((string)(this["CPB_Name_Range"]));
            }
            set {
                this["CPB_Name_Range"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasPrimaryLinkItemId")]
        public string arasPrimaryLinkItemId {
            get {
                return ((string)(this["arasPrimaryLinkItemId"]));
            }
            set {
                this["arasPrimaryLinkItemId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x4_cbp_name")]
        public string CBP_Name_Property_Title {
            get {
                return ((string)(this["CBP_Name_Property_Title"]));
            }
            set {
                this["CBP_Name_Property_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"a_CBP\" action=\"get\" select=\"id,x4_cbp_doc,x4_cbp_name\"></Item></" +
            "AML>")]
        public string AML_to_get_all_CBPs {
            get {
                return ((string)(this["AML_to_get_all_CBPs"]));
            }
            set {
                this["AML_to_get_all_CBPs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x4_cbp_doc")]
        public string CBP_DOCID_Property_Title {
            get {
                return ((string)(this["CBP_DOCID_Property_Title"]));
            }
            set {
                this["CBP_DOCID_Property_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"ItemType\" action=\"get\" select=\"name\">\r\n<name>Document</name>\r\n" +
            "<Relationships>\r\n<Item type=\"Property\" action=\"get\" where=\"[Property].name like " +
            "\'arch_desc%\'\" select=\"name\"></Item>\r\n\r\n</Relationships>\r\n</Item>\r\n\r\n</AML>")]
        public string ArchCountAML {
            get {
                return ((string)(this["ArchCountAML"]));
            }
            set {
                this["ArchCountAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("url")]
        public string ArasURL {
            get {
                return ((string)(this["ArasURL"]));
            }
            set {
                this["ArasURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string SALTUserLogin {
            get {
                return ((string)(this["SALTUserLogin"]));
            }
            set {
                this["SALTUserLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db")]
        public string ARASdb {
            get {
                return ((string)(this["ARASdb"]));
            }
            set {
                this["ARASdb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string SALTUserPassword {
            get {
                return ((string)(this["SALTUserPassword"]));
            }
            set {
                this["SALTUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arch_name_")]
        public string CBPArchname {
            get {
                return ((string)(this["CBPArchname"]));
            }
            set {
                this["CBPArchname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arch_desc_")]
        public string CBPArchDesc {
            get {
                return ((string)(this["CBPArchDesc"]));
            }
            set {
                this["CBPArchDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int numberofArchitecturs {
            get {
                return ((int)(this["numberofArchitecturs"]));
            }
            set {
                this["numberofArchitecturs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Architectures")]
        public string ArchetictureWorksheetName {
            get {
                return ((string)(this["ArchetictureWorksheetName"]));
            }
            set {
                this["ArchetictureWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CBPUpdateConfig.xml")]
        public string ConfigFileName {
            get {
                return ((string)(this["ConfigFileName"]));
            }
            set {
                this["ConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ArasInfo")]
        public string ArasInfoNodeName {
            get {
                return ((string)(this["ArasInfoNodeName"]));
            }
            set {
                this["ArasInfoNodeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasDocumentID")]
        public string ArasDocumentIDCPName {
            get {
                return ((string)(this["ArasDocumentIDCPName"]));
            }
            set {
                this["ArasDocumentIDCPName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arasPrimaryLinkItemId")]
        public string ArasPrimaryLinkIDName {
            get {
                return ((string)(this["ArasPrimaryLinkIDName"]));
            }
            set {
                this["ArasPrimaryLinkIDName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow\" action=\"get\"><source_id></source_id></Item></AML>")]
        public string getWorkFlowAML {
            get {
                return ((string)(this["getWorkFlowAML"]));
            }
            set {
                this["getWorkFlowAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML><Item type=\"Workflow Process\" action=\"get\"><id></id></Item></AML>")]
        public string getWorkFlowProcessAML {
            get {
                return ((string)(this["getWorkFlowProcessAML"]));
            }
            set {
                this["getWorkFlowProcessAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"Workflow Map\" action=\"get\" select=\"name\">\r\n<id></id>\r\n</Item>\r" +
            "\n\r\n</AML>")]
        public string getWorkflowMapNameAML {
            get {
                return ((string)(this["getWorkflowMapNameAML"]));
            }
            set {
                this["getWorkflowMapNameAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hidden")]
        public string HiddenWorksheetName {
            get {
                return ((string)(this["HiddenWorksheetName"]));
            }
            set {
                this["HiddenWorksheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"Workflow Process Activity\" action=\"get\" select=\"related_id\">\r\n" +
            "<source_id></source_id>\r\n</Item>\r\n</AML>")]
        public string getActivitiesAML {
            get {
                return ((string)(this["getActivitiesAML"]));
            }
            set {
                this["getActivitiesAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"Activity Task\" action=\"get\" select=\"sequence,is_required,descr" +
            "iption\">\r\n<source_id></source_id>\r\n</Item>\r\n\r\n</AML>")]
        public string getTasksAML {
            get {
                return ((string)(this["getTasksAML"]));
            }
            set {
                this["getTasksAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"Workflow Process Path\" action=\"get\">\r\n<source_id></source_id>\r" +
            "\n</Item>\r\n\r\n</AML>")]
        public string getVotePaths {
            get {
                return ((string)(this["getVotePaths"]));
            }
            set {
                this["getVotePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<AML>
<Item type=""Activity"" action=""EvaluateActivity"">
<Activity></Activity>
<ActivityAssignment></ActivityAssignment>
<Paths>
<Path></Path>
</Paths>
<Tasks>
<Task id='' completed=""1""></Task>
</Tasks>
<Variables>
</Variables>
<Authentication mode=""""></Authentication>
<Comment></Comment>
<Complete>1</Complete>
</Item>
</AML>")]
        public string completeActivityAML {
            get {
                return ((string)(this["completeActivityAML"]));
            }
            set {
                this["completeActivityAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"Activity Assignment\" action=\"get\">\r\n<source_id></source_id>\r\n<" +
            "/Item>\r\n\r\n</AML>")]
        public string getActivityAssignement {
            get {
                return ((string)(this["getActivityAssignement"]));
            }
            set {
                this["getActivityAssignement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<AML>\r\n<Item type=\"User\" action=\"get\" select=\"owned_by_id\">\r\n<id></id>\r\n</Item>\r\n" +
            "</AML>")]
        public string getLoggedInIdentityID {
            get {
                return ((string)(this["getLoggedInIdentityID"]));
            }
            set {
                this["getLoggedInIdentityID"] = value;
            }
        }
    }
}
